### ISSUE TITLE
[RDS] RDS database root user password

### ISSUE THREAD

**Issue by gozer** [Nubisproject/nubis-stacks#98]
From https://mana.mozilla.org/wiki/display/SECURITY/Nubis#Nubis-#rdsrootpassword

RDS database root user password

It's unclear how the root user is setup in RDS, assuming that the password is not left as this default value in the template.

```
https://github.com/Nubisproject/nubis-stacks/blob/cde5aa4ed0b2a35aff28ad194b1a03fe163dc899/rds-mysql.template#L162
https://github.com/Nubisproject/nubis-stacks/blob/cde5aa4ed0b2a35aff28ad194b1a03fe163dc899/rds-postgres.template#L133
```

Recommendations :

Document how RDS database root user passwords are managed

**Comment by gene1wood** [comment]
Some potential notes about how this works can be found here : https://mana.mozilla.org/wiki/display/SECURITY/Nubis#Nubis-#rdsrootpassword

**Comment by gene1wood** [comment]
Here's the document that was written : https://github.com/Nubisproject/nubis-stacks/blob/master/rds-mysql.README.md#root-password

**Comment by gdestuynder** [comment]
We have lowered the risk to MEDIUM as this is now documented - otherwise, the root password can be used to also create new accounts/privilegied RDS accounts from the instance. This is not a huge issue (hence the MEDIUM), albeit ideally separated instance-related RDS user and root RDS user would be good.

**Comment by gozer** [comment]
I understand the risk from an intellectual point of view.

However, I am curious as to the more practical applications. In this model of one application per account, for instance. In this model of isolation with one account per app, for say, bugzilla.

Assuming an attacker gains code execution on one of the bugzilla nodes, what is the practical security impact of the attacker being able to create a new database or a new database user?

Understanding this would help me better understand the risk. If the password was not the default, randomly picked at bootstrap time, the attacker could still acquire it and achieve the same results. No?

**Comment by gdestuynder** [comment]
There's a couple of threats we discussed (infosec) and I should have put them in the issue earlier, sorry about that.

1) Encourage app to use diff accounts for different tasks, in case of a bug in the app running, the non-root account would normally not be able to modify other db user's accounts. It's good practice to use multiple users with different ACLs inside the same app. Sadly, bugzilla does not do this (yet at least).

2) Attacker creates an account for later use, and we might miss it, helps for persistence (i.e. can re-take db control)

**Comment by tinnightcap** [comment]
@gdestuynder as this issue was closed with all original risk mitigated, I would ask that you open a separate issue and tag name for the new scope that you outlined above. Additionally the original risk tag named #rdsrootpassword should be remedied and a new risk initiated. That risk is only about documenting, we documented.

Thanks
